/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Febuntux;

import java.awt.Desktop;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;

/**
 *
 * @author josda
 */
public class VideosSO extends javax.swing.JFrame {

    /**
     * Creates new form VideosSO
     */
    public VideosSO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        rSButtonCircle4 = new rojerusan.RSButtonCircle();
        rSButtonCircle3 = new rojerusan.RSButtonCircle();
        rSButtonCircle2 = new rojerusan.RSButtonCircle();
        rSButtonCircle1 = new rojerusan.RSButtonCircle();
        rSButtonCircle5 = new rojerusan.RSButtonCircle();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("VIDEOS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        rSButtonCircle4.setBackground(new java.awt.Color(0, 0, 0));
        rSButtonCircle4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/w7.jpg"))); // NOI18N
        rSButtonCircle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonCircle4ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonCircle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 150, 150));

        rSButtonCircle3.setBackground(new java.awt.Color(0, 0, 0));
        rSButtonCircle3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ubuntu.jpg"))); // NOI18N
        rSButtonCircle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonCircle3ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonCircle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 150, 150));

        rSButtonCircle2.setBackground(new java.awt.Color(0, 0, 0));
        rSButtonCircle2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/suse.jpg"))); // NOI18N
        rSButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonCircle2ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 150, 160));

        rSButtonCircle1.setBackground(new java.awt.Color(0, 0, 0));
        rSButtonCircle1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/XP.jpg"))); // NOI18N
        rSButtonCircle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonCircle1ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 150, 160));

        rSButtonCircle5.setBackground(new java.awt.Color(0, 0, 0));
        rSButtonCircle5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fedora2.jpg"))); // NOI18N
        rSButtonCircle5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonCircle5ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonCircle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 150, 150));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proBasicos.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 900, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonCircle5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonCircle5ActionPerformed
        // TODO add your handling code here:
        URL url=null;
try {
    url = new URL("https://drive.google.com/open?id=1ZlfyydMo9IHYYUx92VYJU6kLEBSvCGEf");
    try {
        Desktop.getDesktop().browse(url.toURI());
    } catch (IOException e) {
        e.printStackTrace();
    } catch (URISyntaxException e) {
        e.printStackTrace();
    }
} catch (MalformedURLException e1) {
    e1.printStackTrace();
}
        
    }//GEN-LAST:event_rSButtonCircle5ActionPerformed

    private void rSButtonCircle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonCircle1ActionPerformed
        // TODO add your handling code here:https://drive.google.com/open?id=1IOAlhJxG14HtMRCAqeSzJXeuvBRfvA2G
                URL url=null;
try {
    url = new URL("https://drive.google.com/open?id=1IOAlhJxG14HtMRCAqeSzJXeuvBRfvA2G");
    try {
        Desktop.getDesktop().browse(url.toURI());
    } catch (IOException e) {
        e.printStackTrace();
    } catch (URISyntaxException e) {
        e.printStackTrace();
    }
} catch (MalformedURLException e1) {
    e1.printStackTrace();
}
    }//GEN-LAST:event_rSButtonCircle1ActionPerformed

    private void rSButtonCircle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonCircle3ActionPerformed
        // TODO add your handling code here:
         URL url=null;
try {
    url = new URL("https://drive.google.com/open?id=1_DQx324CU-HhyjzuW6mWSw-MOIzYdZZo");
    try {
        Desktop.getDesktop().browse(url.toURI());
    } catch (IOException e) {
        e.printStackTrace();
    } catch (URISyntaxException e) {
        e.printStackTrace();
    }
} catch (MalformedURLException e1) {
    e1.printStackTrace();
}
    }//GEN-LAST:event_rSButtonCircle3ActionPerformed

    private void rSButtonCircle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonCircle4ActionPerformed
        // TODO add your handling code here:
         URL url=null;
try {
    url = new URL("https://drive.google.com/open?id=1dtDRau4SGMO3vp5_N86-FOiqdMIhjTi6");
    try {
        Desktop.getDesktop().browse(url.toURI());
    } catch (IOException e) {
        e.printStackTrace();
    } catch (URISyntaxException e) {
        e.printStackTrace();
    }
} catch (MalformedURLException e1) {
    e1.printStackTrace();
}
    }//GEN-LAST:event_rSButtonCircle4ActionPerformed

    private void rSButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonCircle2ActionPerformed
        // TODO add your handling code here:
         URL url=null;
try {
    url = new URL("https://drive.google.com/open?id=1IOAlhJxG14HtMRCAqeSzJXeuvBRfvA2G");
    try {
        Desktop.getDesktop().browse(url.toURI());
    } catch (IOException e) {
        e.printStackTrace();
    } catch (URISyntaxException e) {
        e.printStackTrace();
    }
} catch (MalformedURLException e1) {
    e1.printStackTrace();
}
    }//GEN-LAST:event_rSButtonCircle2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SO so = new SO();
        so.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VideosSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VideosSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VideosSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VideosSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VideosSO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private rojerusan.RSButtonCircle rSButtonCircle1;
    private rojerusan.RSButtonCircle rSButtonCircle2;
    private rojerusan.RSButtonCircle rSButtonCircle3;
    private rojerusan.RSButtonCircle rSButtonCircle4;
    private rojerusan.RSButtonCircle rSButtonCircle5;
    // End of variables declaration//GEN-END:variables
}
